site_name: ArqDsw - EnCare

repo_name: "2020.2_G2_Encare"
repo_url: "https://github.com/UnBArqDsw2020-2/2020.2_G2_Encare"

nav:
  - Home: index.md
  - Base:
      - Projeto Não Orientado a Abordagens Específicas:
          - Glossário: Base/glossario/glossario.md
          - Design Sprint: Base/design_sprint.md
          - Rich Picture: Base/rich_picture.md
          - Estimativas: Base/estimativas.md
          - Mapa mental: Base/mapa_mental.md
          - Causa e efeito: Base/causa_e_efeito.md
          - Plano de Ação: Base/planodeacao/5w2g.md
      - Processos/Metodologias/Abordagens:
          - Modelagem BPMN: Base/modelagem_bpmn.md
          - Metodologia: Base/metodologia.md
  - Modelagem:
      - Diagramas Estáticos:
          - Digrama de Componentes: Modelagem/diagrama_componentes.md
          - Diagrama de Classe: Modelagem/diagrama_de_classes.md
      - Diagramas Dinâmicos:
          - Diagrama de Sequência: Modelagem/Diagrama de sequência.md
          - Diagrama de Atividade: Modelagem/diagrama_de_atividades.md
      - Modelagem ágil:
          - Backlog do produto: Modelagem/Backlog.md
  - Iniciativas extras: 
      - Documentação das sprints:
          - Sprints: Modelagem/Sprints.md
      - Requisitos: Base/requisitos.md
      - Politicas de contribuição: Base/iniciativas_extras/CONTRIBUTING.md
theme:
  name: material
  language: pt
  palette:
    primary: blue
